steps:
  - label: Build Optimised Skylake Docker Image
    command: build.sh
    agents:
      queue: "release"
    env:
      MARCH: "skylake"
      PYTHON_VERSION: "3.7.4"
    artifact_paths:
      - "docker.tar.gz"
    retry:
      automatic:
        - exit_status: -1
          limit: 2
        - exit_status: 2
          limit: 2