env:
  COVERALLS_REPO_TOKEN: wsJWOby6j0uCYFiCes3r0XauxO27mx8lD

steps:
  - label: ":python: 3.5 / SQLite"
    command:
      - "openssl version"
    plugins:
      - docker#v3.0.1:
          image: "python:3.5"
          workdir: "/src"
          mount-buildkite-agent: false
          propagate-environment: true
