steps:
  - label: ":eslint: Lint"
    command:
      - "npm install"
      - "npm run lint"
    plugins:
      - docker#v3.0.1:
          image: "node:12"

  - label: ":nodejs: 10 :mocha: Unit/Integration Test"
    command:
      - "npm install"
      - "npm run build"
      - "npm run test"
    plugins:
      - docker#v3.0.1:
          image: "node:10"

  - label: ":nodejs: 12 :mocha: Unit/Integration Test"
    command:
      - "npm install"
      - "npm run build"
      - "npm run test"
    plugins:
      - docker#v3.0.1:
          image: "node:12"
