steps:
  - label: ":eslint: JS Lint"
    command:
      - "yarn install"
      - "yarn lint:js"
    plugins:
      - docker#v3.0.1:
          image: "node:12"
          mount-buildkite-agent: false

  - label: ":jest: Tests"
    command:
      - "yarn install"
      - "yarn test"
    plugins:
      - docker#v3.0.1:
          image: "node:12"
          mount-buildkite-agent: false
