steps:
  - command:
      - "env"
      # https://github.com/golangci/golangci-lint#memory-usage-of-golangci-lint
      - "GOGC=20 ./scripts/find-lint.sh"
    label: "\U0001F9F9 Lint / :go: 1.12"
    agents:
      # Use a larger instance as linting takes a looot of memory
      queue: "medium"
    plugins:
      - docker#v3.0.1:
          image: "golang:1.12"
          mount-buildkite-agent: false

  - wait

  - command:
      - "env"
      - "go build ./cmd/..."
    label: "\U0001F528 Build / :go: 1.11"
    plugins:
      - docker#v3.0.1:
          image: "golang:1.11"
          mount-buildkite-agent: false
    retry:
      automatic:
        - exit_status: 128
          limit: 3

  - command:
      - "env"
      - "go build ./cmd/..."
    label: "\U0001F528 Build / :go: 1.12"
    plugins:
      - docker#v3.0.1:
          image: "golang:1.12"
          mount-buildkite-agent: false
    retry:
      automatic:
        - exit_status: 128
          limit: 3

  - command:
      - "env"
      - "go test ./..."
    label: "\U0001F9EA Unit tests / :go: 1.11"
    plugins:
      - docker#v3.0.1:
          image: "golang:1.11"
          mount-buildkite-agent: false

  - command:
      - "env"
      - "go test ./..."
    label: "\U0001F9EA Unit tests / :go: 1.12"
    plugins:
      - docker#v3.0.1:
          image: "golang:1.12"
          mount-buildkite-agent: false
