# Use Docker file from https://hub.docker.com/r/runmymind/docker-android-sdk
# Last docker plugin version can be found here:
# https://github.com/buildkite-plugins/docker-buildkite-plugin/releases

# Build debug version of the Riot application, from the develop branch and the features branches, with the develop branch of the matrix SDK

steps:
  - label: ":android: Assemble GPlay Debug version"
    agents:
        # build on the burn-after-use ephemeral queue
        queue: "ephemeral-xlarge"
    commands:
      - "./set_debug_env.sh"
      - "./gradlew --no-daemon clean lintAppRelease assembleAppDebug --stacktrace"
    artifact_paths:
      - "vector/build/outputs/apk/app/debug/*.apk"
    branches: "develop feature/*"
    plugins:
      - docker#v3.1.0:
          image: "runmymind/docker-android-sdk"
          mount-buildkite-agent: false

  - label: "Assemble FDroid Debug version"
    agents:
        # build on the burn-after-use ephemeral queue
        queue: "ephemeral-xlarge"
    commands:
      - "./set_debug_env.sh"
      - "./gradlew --no-daemon clean lintAppfdroidRelease assembleAppfdroidDebug --stacktrace"
    artifact_paths:
      - "vector/build/outputs/apk/appfdroid/debug/*.apk"
    branches: "develop feature/*"
    plugins:
      - docker#v3.1.0:
          image: "runmymind/docker-android-sdk"
          mount-buildkite-agent: false

  - label: ":android: Build Google Play unsigned Release APK"
    agents:
        # We use a medium sized instance instead of the normal small ones because
        # gradle build is long
        queue: "xlarge"
    commands:
      - "./gradlew --no-daemon clean assembleAppRelease --stacktrace"
    artifact_paths:
      - "vector/build/outputs/apk/app/release/*.apk"
    branches: "master"
    plugins:
      - docker#v3.1.0:
          image: "runmymind/docker-android-sdk"
          mount-buildkite-agent: false

  - label: ":lint-roller: Code quality"
    commands:
      - apt-get update
      - DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y wget perl-modules
      - ./tools/check/check_code_quality.sh
    plugins:
      - docker#v3.1.0:
          image: "debian:buster-slim"
          mount-buildkite-agent: false
