steps:
  - label: "\U0001F9F9 Check Style and packaging"
    command:
      - "python -m pip install tox"
      - "tox -e packaging lint"
    plugins:
      - docker#v3.0.1:
          image: "python:3.6"
          mount-buildkite-agent: false

  - label: "tests"
    command:
      - "python -m pip install tox"
      - "tox -e test"
    plugins:
      - docker#v3.0.1:
          image: "python:3.6"
          mount-buildkite-agent: false
