version: '3.1'

services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: postgres
    command: -c fsync=off

  testenv:
    image: node:12
    depends_on:
      - postgres
    environment:
      IRCBRIDGE_TEST_PGDB: "ircbridge_integtest"
      IRCBRIDGE_TEST_PGURL: "postgresql://postgres:postgres@postgres"
      IRCBRIDGE_TEST_ENABLEPG: "yes"
    working_dir: /app
    volumes:
      - ..:/app
    command: "bash -c 'yarn && yarn test'"
