steps:
  - label: ":eslint: Lint"
    command:
      - "yarn"
      - "yarn lint"
    plugins:
      - docker#v3.0.1:
          image: "node:12"
          mount-buildkite-agent: false

  - label: ":jasmine: Tests Node 10"
    command:
      - "yarn"
      - "yarn test"
    plugins:
      - docker#v3.0.1:
          image: "node:10"
          mount-buildkite-agent: false

  - label: ":jasmine: Tests Node 12"
    command:
      - "yarn"
      - "yarn test"
    plugins:
      - docker#v3.0.1:
          image: "node:12"
          mount-buildkite-agent: false

  - label: ":nyc: Coverage"
    command:
      - "yarn"
      - "yarn ci-test"
    plugins:
      - docker#v3.0.1:
          image: "node:12"
          mount-buildkite-agent: false

  - label: ":newspaper: Newsfile"
    branches: "!master !develop !release-*"
    command:
      - "python3 -m pip install towncrier"
      - "python3 -m towncrier.check --compare-with=origin/develop"
    plugins:
      - docker#v3.0.1:
          image: "python:3.6"
          propagate-environment: true
          mount-buildkite-agent: false