steps:
  - command:
      - "echo '--- Install towncrier'"
      - "pip install towncrier"
      - "echo '+++ Check newsfile'"
      - "python -m towncrier.check --compare-with='origin/main'"
    label: ":rolled_up_newspaper: Newsfile"
    plugins:
      - docker#v3.0.1:
          image: "python:3.6"
          mount-buildkite-agent: false
    branches: "!master !release-*"

  - command:
      - "echo '--- Install dependencies'"
      - "pip install -e ."
      - "echo '+++ Run unit tests'"
      - "trial tests"
    label: ":partyparrot: Unit tests / :python: 3.6"
    plugins:
      - docker#v3.0.1:
          image: "python:3.6"
          mount-buildkite-agent: false
    artifact_paths:
      - "_trial_temp/test.log"

  - command:
      - "echo '--- Install dependencies'"
      - "pip install -e ."
      - "echo '--- Install matrix_is_tester'"
      - "pip install git+https://github.com/matrix-org/matrix-is-tester.git"
      - "echo '+++ Run Tests'"
      - "trial matrix_is_tester"
    label: ":pytest: matrix_is_tester / :python: 3.6"
    timeout_in_minutes: 5
    plugins:
      - docker#v3.0.1:
          image: "python:3.6"
          mount-buildkite-agent: false
    artifact_paths:
      - "matrix_is_test/sydent.stderr"
      - "_trial_temp/test.log"

  - command:
      - "echo '--- Install dependencies'"
      - "pip install -e ."
      - "echo '+++ Run unit tests'"
      - "trial tests"
    label: ":partyparrot: Unit tests / :python: 3.9"
    plugins:
      - docker#v3.0.1:
          image: "python:3.9"
          mount-buildkite-agent: false
    artifact_paths:
      - "_trial_temp/test.log"

  - command:
      - "echo '--- Install dependencies'"
      - "pip install -e ."
      - "echo '--- Install matrix_is_tester'"
      - "pip install git+https://github.com/matrix-org/matrix-is-tester.git"
      - "echo '+++ Run Tests'"
      - "trial matrix_is_tester"
    label: ":pytest: matrix_is_tester / :python: 3.9"
    timeout_in_minutes: 5
    plugins:
      - docker#v3.0.1:
          image: "python:3.9"
          mount-buildkite-agent: false
    artifact_paths:
      - "matrix_is_test/sydent.stderr"
      - "_trial_temp/test.log"
